
name: Verify

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
      
      - name: Install dependencies
        run: npm install
      
      - name: Check
        run: npm run check
